import { defineConfig } from '@playwright/test';
import path from 'path';
import os from 'os';

/**
 * Minimal Playwright Configuration for API Testing Feature
 * 
 * This config is used when executing API tests generated by the application.
 * It avoids starting a web server since the application is already running.
 */
export default defineConfig({
    testDir: path.join(os.tmpdir(), 'api-generated'),

    // Reporter is handled by the executor command line args, but setting default here doesn't hurt
    reporter: 'json',

    use: {
        /* Base URL to use in actions like `await request.get('/')` */
        baseURL: process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:3000',

        /* Collect trace when retrying the failed test */
        trace: 'retain-on-failure',
    },

    /* Configure projects */
    projects: [
        {
            name: 'api',
            use: {},
        },
    ],
});
